// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/medlink-redesign/BranchManager.tsx": () => import("../components/mockups/medlink-redesign/BranchManager.tsx"),
  "./components/mockups/medlink-redesign/Client.tsx": () => import("../components/mockups/medlink-redesign/Client.tsx"),
  "./components/mockups/medlink-redesign/Driver.tsx": () => import("../components/mockups/medlink-redesign/Driver.tsx")
};
