import "./_group.css";
import { AlertTriangle, ChevronLeft, ClipboardList, Edit3, Package, Plus, Truck, Users, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import type { ReactNode } from "react";
import { Nav, Screen, TopBar } from "./_shared/AppShell";
export function BranchManager() {
  const [tab,setTab]=useState("dashboard"); const [toast,setToast]=useState("");
  const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),1800)};
  return <Screen><TopBar role="branch" onBell={()=>notify("تنبيه: ٣ طلبات جديدة")}/><main className="ml-content">
   {tab==="dashboard"&&<><p className="ml-kicker">BRANCH CONTROL / SA-07</p><h1 className="ml-title">موجز الفرع</h1><p className="ml-sub">فرع التحرير · آخر مزامنة قبل ٣ دقائق</p><div className="ml-grid" style={{marginTop:20}}><Stat icon={<ClipboardList size={16}/>} label="طلبات جديدة" value="١٢" tone="orange"/><Stat icon={<Truck size={16}/>} label="قيد التوصيل" value="٠٧"/><Stat icon={<CheckCircle2 size={16}/>} label="مكتملة اليوم" value="٣٤" tone="green"/></div><div className="ml-section-head"><h3>أحدث الطلبات</h3><button className="ml-link" onClick={()=>setTab("orders")}>كل الطلبات</button></div><div className="ml-list">{orders.map((o,i)=><Order key={o.id} {...o} onClick={()=>notify(i===0?"تم فتح تفاصيل الطلب":"جار تجهيز العرض")}/>)}</div></>}
   {tab==="orders"&&<><p className="ml-kicker">INCOMING / 86 ORDERS</p><h1 className="ml-title">الطلبات الواردة</h1><div className="ml-chips" style={{margin:"18px 0"}}>{["الكل","جديد","تم الإسناد","قيد التوصيل"].map((x,i)=><button className={`ml-chip ${i===0?"active":""}`} key={x}>{x}</button>)}</div><div className="ml-list">{orders.concat([{id:"#ML-47991",name:"مستوصف الحياة",time:"أمس 18:20",value:"١١٬٧٥٠ ر.ي",status:"تم الإسناد"}]).map(o=><Order key={o.id} {...o} onClick={()=>notify("خيارات الطلب: إسناد سائق أو تحويل")}/>)}</div></>}
   {tab==="inventory"&&<><p className="ml-kicker">STOCK / LIVE COUNTS</p><h1 className="ml-title">المخزون</h1><div className="ml-card" style={{marginTop:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><small>قيمة المخزون الحالية</small><strong>٢٬٨٤٠٬٥٠٠ ر.ي</strong></div><Package size={22} color="#66e4e0"/></div><div className="ml-progress"><span style={{width:"78%"}}/></div><small style={{display:"block",marginTop:8}}>استخدام السعة ٧٨٪ · آخر تحديث مباشر</small></div><div className="ml-section-head"><h3>الأصناف التي تحتاج انتباهاً</h3><button className="ml-link" onClick={()=>notify("تمت مزامنة المخزون")}>مزامنة</button></div><div className="ml-list">{["أموكسيسيلين 500mg","شرائط فحص السكر","محلول ملحي 500ml","كمامات طبية"].map((x,i)=><div className="ml-card ml-row" key={x}><div className={`ml-avatar ${i<2?"danger":""}`}><AlertTriangle size={16}/></div><div className="ml-row-main"><strong>{x}</strong><small>{i===0?"متبقي ١٨ عبوة":i===1?"متبقي ٢٤ علبة":"متبقي ٦٥ وحدة"}</small></div><button className="ml-icon-btn" onClick={()=>notify("فتح تعديل الكمية")}><Edit3 size={14}/></button></div>)}</div></>}
   {tab==="drivers"&&<><p className="ml-kicker">FLEET / 08 ACTIVE</p><h1 className="ml-title">السائقون</h1><div className="ml-grid" style={{marginTop:20}}><Stat icon={<Users size={16}/>} label="متاحون الآن" value="٠٥"/><Stat icon={<Truck size={16}/>} label="في مهمة" value="٠٣"/></div><div className="ml-section-head"><h3>الفريق النشط</h3><button className="ml-action" onClick={()=>notify("تم إرسال دعوة سائق")}>دعوة سائق <Plus size={13}/></button></div>{["محمد العريقي","سامر الهاشمي","فارس المقطري"].map((x,i)=><div className="ml-card ml-row" key={x}><div className="ml-avatar"><Truck size={16}/></div><div className="ml-row-main"><strong>{x}</strong><small>آخر تسليم منذ {i+1} ساعة · تقييم ٤.{8-i}</small></div><span className="ml-status">{i===2?"في مهمة":"متاح"}</span></div>)}</>}
  </main><Nav role="branch" active={tab} onChange={setTab}/>{toast&&<div className="ml-toast">{toast}</div>}</Screen>;
}
function Stat({icon,label,value,tone}:{icon:ReactNode;label:string;value:string;tone?:string}){return <div className="ml-card"><div className="ml-stat-icon" style={tone==="orange"?{color:"#ffb86b",background:"rgba(255,184,107,.12)"}:tone==="green"?{color:"#78e0ae",background:"rgba(120,224,174,.12)"}:{}}>{icon}</div><small>{label}</small><strong>{value}</strong></div>}
function Order({id,name,time,value,status,onClick}:{id:string;name:string;time:string;value:string;status:string;onClick:()=>void}){return <button className="ml-card ml-row" onClick={onClick} style={{textAlign:"right",width:"100%",border:"1px solid var(--line)"}}><div className="ml-avatar"><ClipboardList size={16}/></div><div className="ml-row-main"><strong>{id} · {name}</strong><small>{time} · {value}</small><span className="ml-status">{status}</span></div><ChevronLeft size={16} color="#8399a6"/></button>}
const orders=[{id:"#ML-48217",name:"صيدلية الشفاء",time:"منذ ١٢ دقيقة",value:"١٨٬٤٠٠ ر.ي",status:"جديد"},{id:"#ML-48206",name:"مركز المدينة الطبي",time:"منذ ٣٢ دقيقة",value:"٤٢٬٧٥٠ ر.ي",status:"تم الإسناد"},{id:"#ML-48192",name:"صيدلية النور",time:"منذ ساعة",value:"٩٬٣٠٠ ر.ي",status:"قيد التوصيل"}];