import "./_group.css";
import { ArrowLeft, ChevronLeft, HeartPulse, MapPin, Plus, Search, ShoppingCart, Sparkles } from "lucide-react";
import { useState } from "react";
import { Nav, Screen, TopBar } from "./_shared/AppShell";

const products = [["أموكسيسيلين 500mg","مضاد حيوي · 20 كبسولة","١٬٢٥٠ ر.ي"],["باراسيتامول 500mg","مسكن وخافض للحرارة","٨٥٠ ر.ي"],["محلول ملحي 500ml","مستلزمات طبية","٦٥٠ ر.ي"],["فيتامين د3","مكمل غذائي · 30 حبة","٢٬١٠٠ ر.ي"]];
export function Client() {
  const [tab,setTab]=useState("home"); const [toast,setToast]=useState(""); const [query,setQuery]=useState("");
  const add=()=>{setToast("تمت إضافة المنتج إلى السلة");setTimeout(()=>setToast(""),1800)};
  return <Screen><TopBar role="client" onBell={()=>setToast("لديك إشعاران جديدان")}/><main className="ml-content">
    {tab==="home" && <><p className="ml-kicker">CLIENT / HEALTHCARE SUPPLY</p><h1 className="ml-title">مرحباً، صيدلية الشفاء</h1><p className="ml-sub">كل ما تحتاجه لإبقاء رفوفك جاهزة، من مصدر موثوق.</p>
      <section className="ml-hero"><Sparkles size={20} color="#66e4e0"/><h2>توريد أكثر ذكاءً، اليوم</h2><p>خصم خاص على المستلزمات الأساسية عند الطلب قبل ٢٢:٠٠.</p><button className="ml-action" onClick={()=>setTab("catalog")}>استكشف العروض <ArrowLeft size={14} style={{verticalAlign:"middle"}}/></button></section>
      <div className="ml-section-head"><h3>الوصول السريع</h3><button className="ml-link" onClick={()=>setTab("catalog")}>عرض الكل</button></div><div className="ml-chips"><button className="ml-chip active" onClick={()=>setTab("catalog")}>الأكثر طلباً</button><button className="ml-chip" onClick={()=>setTab("catalog")}>أدوية مزمنة</button><button className="ml-chip" onClick={()=>setTab("catalog")}>مستلزمات</button></div>
      <div className="ml-section-head"><h3>طلبك الأخير</h3><button className="ml-link" onClick={()=>setTab("orders")}>سجل الطلبات</button></div><div className="ml-card ml-row"><div className="ml-avatar"><ShoppingCart size={17}/></div><div className="ml-row-main"><strong>طلب #ML-48217</strong><small>فرع شارع الزبيري · منذ ساعتين</small><span className="ml-status">قيد التجهيز</span></div><ChevronLeft size={17} color="#8399a6"/></div>
      <div className="ml-section-head"><h3>منتجات مقترحة</h3></div><ProductStrip add={add}/></>}
    {tab==="catalog" && <><p className="ml-kicker">CATALOG / 248 PRODUCTS</p><h1 className="ml-title">كتالوج الأدوية</h1><div className="ml-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الدواء أو الفئة"/></div><div className="ml-chips"><button className="ml-chip active">الكل</button><button className="ml-chip">أدوية</button><button className="ml-chip">مستلزمات</button></div><div className="ml-list" style={{marginTop:16}}>{products.filter(p=>p[0].includes(query)||!query).map(p=><div className="ml-card ml-row" key={p[0]}><div className="ml-avatar"><HeartPulse size={17}/></div><div className="ml-row-main"><strong>{p[0]}</strong><small>{p[1]}</small></div><div className="ml-value">{p[2]}<button className="ml-icon-btn" onClick={add} style={{marginTop:6,width:28,height:28}}><Plus size={14}/></button></div></div>)}</div></>}
    {tab==="orders" && <><p className="ml-kicker">ORDERS / TRACKING</p><h1 className="ml-title">طلباتي</h1><div className="ml-list" style={{marginTop:20}}>{["#ML-48217","#ML-48102","#ML-47988"].map((id,i)=><div className="ml-card" key={id}><div style={{display:"flex",justifyContent:"space-between"}}><strong>{id}</strong><span className={`ml-status ${i===2?"warn":""}`}>{i===0?"قيد التجهيز":i===1?"تم التوصيل":"قيد المراجعة"}</span></div><div className="ml-ticker"><MapPin size={14} color="#66e4e0"/> صيدلية الشفاء · صنعاء <span className="ml-value">{i===0?"١٨٬٤٠٠":"٢٤٬٦٥٠"} ر.ي</span></div>{i===0&&<div className="ml-progress"><span style={{width:"62%"}}/></div>}</div>)}</div></>}
  </main><Nav role="client" active={tab} onChange={setTab}/>{toast&&<div className="ml-toast">{toast}</div>}</Screen>;
}
function ProductStrip({add}:{add:()=>void}) { return <div className="ml-list">{products.slice(0,2).map(p=><div className="ml-card ml-row" key={p[0]}><div className="ml-avatar"><HeartPulse size={17}/></div><div className="ml-row-main"><strong>{p[0]}</strong><small>{p[1]}</small></div><button className="ml-icon-btn" onClick={add}><Plus size={16}/></button></div>)}</div>; }