import "./_group.css";
import { ArrowLeft, CheckCircle2, ChevronLeft, Clock3, Headphones, MapPin, Navigation, PackageCheck, Truck, Wallet } from "lucide-react";
import { useState } from "react";
import { Nav, Screen, TopBar } from "./_shared/AppShell";
export function Driver(){const [tab,setTab]=useState("orders");const [toast,setToast]=useState("");const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),1800)};return <Screen><TopBar role="driver" onBell={()=>notify("تحديث جديد لمسارك اليوم")}/><main className="ml-content">
 {tab==="orders"&&<><p className="ml-kicker">DRIVER / ROUTE 04</p><h1 className="ml-title">صباح الخير، ياسر</h1><p className="ml-sub">لديك ٣ توصيلات مجدولة · إجمالي المسافة ١٨ كم</p><section className="ml-hero"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p className="ml-kicker" style={{margin:0}}>NEXT STOP</p><h2 style={{marginTop:6}}>صيدلية الشفاء</h2><p style={{margin:0}}>شارع الزبيري · صنعاء</p></div><div className="ml-stat-icon"><Navigation size={18}/></div></div><button className="ml-action" onClick={()=>notify("تم فتح مسار التوصيل")}>ابدأ الملاحة <ArrowLeft size={14} style={{verticalAlign:"middle"}}/></button></section><div className="ml-section-head"><h3>مهام اليوم</h3><span className="ml-kicker" style={{margin:0}}>03 STOPS</span></div><div className="ml-list">{driverOrders.map((o,i)=><button className="ml-card ml-row" key={o.id} onClick={()=>notify(i===0?"تم فتح تفاصيل التوصيل":"تم تحديد المهمة")} style={{textAlign:"right",width:"100%",border:"1px solid var(--line)"}}><div className="ml-avatar"><PackageCheck size={16}/></div><div className="ml-row-main"><strong>{o.id} · {o.place}</strong><small><MapPin size={11} style={{verticalAlign:"middle"}}/> {o.address}</small><span className={`ml-status ${i===1?"warn":""}`}>{o.status}</span></div><ChevronLeft size={16} color="#8399a6"/></button>)}</div></>}
 {tab==="earnings"&&<><p className="ml-kicker">WALLET / MAY 2024</p><h1 className="ml-title">الأرباح</h1><div className="ml-card" style={{marginTop:20,padding:20}}><small>إجمالي أرباح هذا الشهر</small><strong style={{fontSize:30,color:"#66e4e0"}}>٧٨٬٤٥٠ ر.ي</strong><div className="ml-ticker"><CheckCircle2 size={14} color="#78e0ae"/> ٢٨ توصيل مكتمل</div></div><div className="ml-grid" style={{marginTop:12}}><div className="ml-card"><small>هذا الأسبوع</small><strong>١٨٬٢٠٠</strong></div><div className="ml-card"><small>التقييم العام</small><strong>٤.٨ <span style={{fontSize:12,color:"#ffb86b"}}>/ ٥</span></strong></div></div><div className="ml-section-head"><h3>سجل العمولات</h3></div><div className="ml-list">{["#ML-48192"," #ML-48174"," #ML-48151"].map((x,i)=><div className="ml-card ml-row" key={x}><div className="ml-avatar"><Wallet size={16}/></div><div className="ml-row-main"><strong>{x}</strong><small>توصيل مكتمل · {i+1} مايو</small></div><span className="ml-value">+ {i===0?"٢٬٤٠٠":"١٬٨٥٠"} ر.ي</span></div>)}</div></>}
 {tab==="chat"&&<><p className="ml-kicker">SUPPORT / LIVE</p><h1 className="ml-title">مركز الدعم</h1><div className="ml-card" style={{marginTop:20,textAlign:"center",padding:28}}><div className="ml-mark" style={{margin:"0 auto 14px"}}><Headphones size={18}/></div><h2 style={{fontSize:17}}>نحن هنا لمساعدتك</h2><p className="ml-sub">فريق العمليات متاح من ٨ صباحاً حتى ١٠ مساءً.</p><button className="ml-action" onClick={()=>notify("تم فتح محادثة الدعم")}>بدء محادثة</button></div><div className="ml-section-head"><h3>مواضيع سريعة</h3></div>{["مشكلة في عنوان التسليم","تحديث حالة الطلب","استفسار عن العمولة"].map(x=><button className="ml-card ml-row" onClick={()=>notify("تم اختيار: "+x)} key={x} style={{width:"100%",textAlign:"right",border:"1px solid var(--line)",marginBottom:10}}><div className="ml-row-main"><strong>{x}</strong><small>اضغط لإرسال طلب</small></div><ChevronLeft size={16}/></button>)}</>}
 </main><Nav role="driver" active={tab} onChange={setTab}/>{toast&&<div className="ml-toast">{toast}</div>}</Screen>}
const driverOrders=[{id:"#ML-48217",place:"صيدلية الشفاء",address:"شارع الزبيري، صنعاء",status:"جاهز للاستلام"},{id:"#ML-48192",place:"مركز المدينة الطبي",address:"حي الوحدة، صنعاء",status:"مجدول ١٤:٣٠"},{id:"#ML-48174",place:"صيدلية النور",address:"شارع حدة، صنعاء",status:"مجدول ١٦:٠٠"}];